
version: 2

models:
  - name: my_first_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique


  - name: my_second_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: milestone1i
    description: "calculate monthly avg nav"
    columns:
      - name: nav_month
        description: "month for each scheme"
        tests:
          - not_null

  - name: milestone1ii
    description: "max and min value acc to date"
    columns:
      - name: nav_date
        description: "date for each scheme"
        tests:
          - not_null
